name: biodt-hackathon25
channels:
  - conda-forge
dependencies:
  - jupyter
  - jupyterlab
  - nbclassic
  - python=3.12
  - ipykernel
  - scipy
  - nglview
  - r-base=4.3.3
  - r-irkernel
  - rioxarray
  - matplotlib
  - pandas
  - matplotlib-scalebar
  - numpy
  - ipywidgets
  - ipympl
  - r-terra
  - r-raster
  - git
  - minio-client
  - minio
  - s3fs
#  - soilgrids
  - pyproj
  - rdata
  - rasterio
  - requests
  - pip:
    - git+https://github.com/QCDIS/general-soilgrids-soil-data.git
#    - git+https://github.com/trossi/rdata.git@e50eb9c