name: veluwe-forest-model
channels:
  - conda-forge
dependencies:
  - r-renv
  - r-jsonlite
  - r-lobstr
  - r-rlang
  - r-purrr
  - r-optparse
  - r-rcpp
  - r-rcppeigen
  - r-ggplot2
  - git
  - python>=3.9
  - pip
