name: laserfarm
channels:
  - conda-forge
dependencies:
  - asyncssh
  - cxx-compiler
  - dask
  - dask-core
  - distro
  - gcc=12.1.0
  - gdal=3.5.0
  - html5lib
  - ipykernel
  - Jinja2
  - laspy
  - lazrs-python
  - libgcc
  - libstdcxx-ng
  - matplotlib
  - numpy
  - pdal
  - plyfile
  - pyshp
  - python-pdal
  - python>=3.11
  - scipy
  - sentinelhub
  - setuptools
  - shapely
  - wradlib
  - pip:
      - git+https://github.com/QCDIS/Laserfarm.git
      - git+https://github.com/QCDIS/laserchicken.git
