name: vol2bird
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconductor-rhdf5lib
  - h5py
  - ipykernel
  - minio
  - webdavclient3
  - r-devtools
  - git
  - hdf5
  - proj
  - gsl
  - r-terra
  - r-rgdal
