name: vol2bird
channels:
  - conda-forge
  - bioconda
dependencies:
  - h5py
  - ipykernel
  - minio
  - webdavclient3
  - git
  - r-base
  - hdf5
  - pkg-config
  - gdal
  - libgdal
  - libgdal-hdf5
  - openssl
  - proj
  - gsl
  - r-raster
  - r-sf
  - libexpat
  - udunits2
  - bioconductor-rhdf5
  - r-labeling
  - r-bit64
  - r-progress
  - r-cli
  - r-colorspace
  - r-rcolorbrewer
  - r-matrix
  - r-fansi
  - r-dotcall64
  - r-nlme
  - r-munsell
  - r-generics
  - r-tibble
  - r-spam
  - r-maps
  - r-isoband
  - r-mgcv
  - r-scales
  - r-gtable
  - r-utf8
  - r-munsell
  - r-withr
  - r-timechange
  - r-clipr
  - r-vroom
  - r-tzdb
  - r-stringi
  - r-purrr
  - r-curl
  - r-dplyr
  - r-fields
  - r-ggplot2
  - r-jsonlite
  - r-lubridate
  - r-stringr
  - r-tidyr
  - r-tidyselect
  - r-viridis
  - r-readr
  - r-gridextra
  - r-classint
  - r-s2
  - r-proxy
  - r-sf
  - r-wk
  - r-udunits2
