name: lter-life-wadden
channels:
  - conda-forge
dependencies:
  - ipykernel
  - minio
  - webdavclient3
  - r-irkernel
  - r-jsonlite
  - r-optparse
  - r-fme
  - r-desolve
  - r-plot3d
  - r-sf
  - r-ncdf4
  - r-tidyverse