name: lter-life-wadden
channels:
  - conda-forge
  - defaults
dependencies:
  # NaaVRE
  - ipykernel
  - minio
  - webdavclient3
  - r-irkernel
  - r-jsonlite
  - r-optparse
  # Wadden
  - r-fme
  - r-desolve
  - r-plot3d
  - r-sf
  - r-ncdf4
  - r-tidyverse
  - r-devtools
  - git
  # Acolite
  # (Acolite doesn't run on Python 3.12 yet)
  - python<=3.11
  - pyresample
  - cartopy
  - scipy
  - numpy
  - pyhdf
  - gdal
  - libgdal-jp2openjpeg
  - netcdf4
  - h5py
  - pygrib
  - requests
  - matplotlib
  - scikit-image
  - pyproj
