name: wiresits
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - r-base=4.3.3
  - r-lobstr
  - r-rlang
  - r-purrr
  - r-optparse
  - r-rcpp
  - r-rcppeigen
  - r-ggplot2
  - git
  - r-geodata
  - r-ggcorrplot
  - r-ggspatial
  - r-irr
  - r-mlr3measures
  - r-mltools
  - r-pals
  - r-patchwork
  - r-pdp
  - r-progress
  - r-psych
  - r-ptw
  - r-base
 # - r-rgdal package r-rgdal-1.4_3-r35h474ac88_2 requires r-base >=3.5.1,<3.5.2.0a0, but none of the providers can be installed
  - r-rgeos
  - r-rnaturalearth
  - r-scales
  - r-sf
  - r-sp
  - r-terra>=1.8.5
  - r-tidyverse
  - r-zoo
  - r-zyp
  - r-gdalutilities
  - r-hmisc
  - r-metrics
  - r-modistsp
  - r-randomforest
  - r-raster
  - r-rastervis
  - r-rcolorbrewer
