name: quadfavl
channels:
  - conda-forge
  - bioconda
dependencies:
  - h5py
  - ipykernel
  - minio
  - webdavclient3
  - git
  - r-base
  - hdf5
  - pkg-config
  - gdal
  - libgdal
  - libgdal-hdf5
  - openssl
  - proj
  - gsl
  - r-raster
  - r-sf
  - libexpat
  - udunits2
  - bioconductor-rhdf5
  - r-labeling
  - r-bit64
  - r-progress
  - r-cli
  - r-colorspace
  - r-rcolorbrewer
  - r-matrix
  - r-fansi
  - r-dotcall64
  - r-nlme
  - r-munsell
  - r-generics
  - r-tibble
  - r-spam
  - r-maps
  - r-isoband
  - r-mgcv
  - r-scales
  - r-gtable
  - r-utf8
  - r-munsell
  - r-withr
  - r-timechange
  - r-clipr
  - r-vroom
  - r-tzdb
  - r-stringi
  - r-purrr
  - r-curl
  - r-dplyr
  - r-fields
  - r-ggplot2
  - r-jsonlite
  - r-lubridate
  - r-stringr
  - r-tidyr
  - r-tidyselect
  - r-viridis
  - r-readr
  - r-gridextra
  - r-classint
  - r-s2
  - r-proxy
  - r-sf
  - r-wk
  - r-udunits2
  - r-irkernel
  - r-renv
  - r-lobstr
  - r-rlang
  - r-optparse
  - r-rcpp
  - r-rcppeigen
  - nano
  - vim
  - r-askpass
  - r-credentials
  - r-sys
  - r-zip
  - r-gitcreds
  - r-ini
  - r-httpuv
  - r-mime
  - r-xtable
  - r-sourcetools
  - r-later
  - r-promises
  - r-jquerylib
  - r-sass
  - r-systemfonts
  - r-textshaping
  - r-tinytex
  - r-xfun
  - r-highr
  - r-diffobj
  - r-gert
  - r-gh
  - r-rappdirs
  - r-rprojroot
  - r-rstudioapi
  - r-whisker
  - r-yaml
  - r-cachem
  - r-shiny
  - r-callr
  - r-processx
  - r-bslib
  - r-downlit
  - r-fontawesome
  - r-httr2
  - r-openssl
  - r-ragg
  - r-rmarkdown
  - r-xml2
  - r-htmlwidgets
  - r-xopen
  - r-brew
  - r-commonmark
  - r-knitr
  - r-brio
  - r-praise
  - r-ps
  - r-waldo
  - r-usethis
  - r-desc
  - r-fs
  - r-memoise
  - r-miniUI
  - r-pkgbuild
  - r-pkgdown
  - r-pkgload
  - r-profvis
  - r-rcmdcheck
  - r-remotes
  - r-roxygen2
  - r-rversions
  - r-sessioninfo
  - r-testthat
  - r-urlchecker
  - r-devtools
  - r-codetools
  - r-keyring