name: Make

on:
  release:
    types: [published]
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  schedule:
    - cron: '0 4 5,25 * *'

jobs:
  list-flavors:
    name: List flavors
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.list-flavors.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: list-flavors
        name: List flavors
        run: |
          matrix=$(find ./flavors -mindepth 2 -maxdepth 2 -name 'flavor_config.yaml' | xargs yq ea -o=j -I=0 '[.]')
          echo "matrix={\"include\":$(echo $matrix)}" >> $GITHUB_OUTPUT

  flavors:
    name: Flavor ${{ matrix.flavor_name }}
    uses: ./.github/workflows/make-flavor.yaml
    needs: [list-flavors]
    with:
      flavor_name: ${{ matrix.flavor_name }}
      image_repo: 'ghcr.io/qcdis/naavre'
      image_version: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
      naavre_version: 'v2.3.3-beta'
      build_jupyter: ${{ matrix.build_jupyter }}
    strategy:
      matrix: ${{ fromJson(needs.list-flavors.outputs.matrix) }}
