name: Push image

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Docker image name'
        type: string
        required: true
      image_repo:
        description: 'Docker image repo'
        type: string
        required: true
      free_disk_space:
        description: 'Free disk space on the action runner before running jobs'
        type: boolean
        required: false
        default: false

jobs:
  push:
    name: Push ${{ inputs.image_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Free Up GitHub Actions Ubuntu Runner Disk Space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: true
        if: ${{ inputs.free_disk_space }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.image_name }}
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/${{ inputs.image_name }}.tar
          docker image ls -a

      - name: Login to container registry
        uses: docker/login-action@v3
        env:
          REGISTRY_NAME: ${{ vars.REGISTRY_NAME || 'ghcr.io' }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME || github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD || secrets.GITHUB_TOKEN }}
        with:
          registry: ${{ env.REGISTRY_NAME }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Push image
        run: |
          docker push ${{ inputs.image_repo }}/${{ inputs.image_name }} --all-tags
