name: Test cell base image

on:
  workflow_call:
    inputs:
      image_name_build:
        description: 'Docker image name for build stage'
        type: string
        required: true
      image_name_runtime:
        description: 'Docker image name for runtime stage'
        type: string
        required: true
      image_repo:
        description: 'Docker image repo'
        type: string
        required: true
      tests_dir:
        description: 'Directory containing test files'
        type: string
        required: true

jobs:
  test:
    name: Test ${{ inputs.image_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.image_name_build }}
          path: /tmp

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.image_name_runtime }}
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/${{ inputs.image_name_build }}.tar
          docker image ls -a

      - name: Load image
        run: |
          docker load --input /tmp/${{ inputs.image_name_runtime }}.tar
          docker image ls -a

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/cell-test.Dockerfile
          build-args: |
            BUILD_IMAGE=${{ inputs.image_repo }}/${{ inputs.image_name_build }}
            RUNTIME_IMAGE=${{ inputs.image_repo }}/${{ inputs.image_name_runtime }}
          tags: cell_test
          cache-from: type=gha
          cache-to: type=gha,mode=min

      - name: Run tests
        run: |
          docker run -v ${{ inputs.tests_dir }}:/tests/ cell_test /bin/bash /tests/tests.sh
